export const data = [
	{
		activities: ['water sports', 'camping'],
		tags: ['domestic', 'family', 'honeymoon'],
		slug: 'andaman-and-nicobar',
		src: '/destinations/andamannicobar.jpg',
		name: 'Andaman and Nicobar',
		duration: '5 nights, 6 days',
		d_days: 6,
		price: 20000,
		available: {
			jan: true,
			feb: true,
			mar: true,
			apr: true,
			may: true,
			jun: true,
			jul: true,
			aug: true,
			sep: true,
			oct: true,
			nov: true,
			dec: true,
		},
		days: [
			{
				day: '1',
				title: 'Port Blair : Arrival and Sightseeing',
				desc: 'Reach port blair airport where our representative will welcome you. Get transferred to the hotel, complete the check-in process and enjoy a scrumptious lunch. After having some rest, proceed for a tour of the cellular jail which narrates the saga of the indian freedom struggle. Enjoy a soul-stirring light & sound show in the evening. Later, make your way back to the hotel for an overnight stay',
			},
			{
				day: '2',
				title: 'Port Blair: Excursion to Ross & North Bay Islands',
				desc: 'Wake up to an appetizing breakfast and head out to explore the colonial ruins at ross island. Later, set off on a watery trail with the next destination i.e. North bay island. Here, you can enjoy a glass bottom ride and witness the underwater corals. Enjoy an overnight stay at port blair. Note: the north bay island is closed on wednesdays.',
			},
			{
				day: '3',
				title: 'Havelock : Arrival & Sightseeing',
				desc: 'Have a relishing breakfast, and catch a ferry to havelock island. After arriving, check-in at the hotel and have lunch. After refreshing yourself, proceed towards radhanagar beach where you can enjoy swimming, and also other water activities. Enjoy an overnight stay at the hotel in havelock island. Note: paid showers & changing room facilities available on radhanagar beach.',
			},
			{
				day: '4',
				title: 'Neil Island : Arrival & Sightseeing',
				desc: 'After your breakfast at the hotel, check out and proceed towards neil island. Reach your pre-booked hotel, complete the check-in process, and spend some leisurely time. Later, head for the famous bharatpur and laxmanpur beaches. You can either part in water sports or spend cozy moments by the beach. Get back to the hotel for an overnight stay at neil island.',
			},
			{
				day: '5',
				title: 'Port Blair : Arrival & Leisure',
				desc: 'Enjoy your breakfast at your hotel and prepare for departure from neil island back to port blair. On arrival at port blair, check in to your hotel and have some rest. In the evening, you can visit the shopping center at port blair to buy souvenirs and gifts. Have a goodnight sleep at the hotel in port blair.',
			},
			{
				day: '6',
				title: 'Departure',
				desc: 'Drop at airport drop to port blair airport for return journey with wonderful holiday memories',
			},
		],
		inclusions: [
			'5 nights air conditioned accommodation at all places',
			'Return airport / harbor transfers by private a/c vehicle as per the itinerary sightseeing and all transfers in private a/c vehicle as per the itinerary (innova crysta) all entry permits/ tickets, ferry tickets and forest area permits wherever applicable return havelock / neil ferry transfer in deluxe ferry - MV Makruzz / green ocean : premium class / Executive class (subject to availability) ',
			'(if private ferries are not operating due to climatic conditions / technical maintenance or any other reasons, then the guests will be shifted to government ferry)',
			'Assistance at all arrival and departure points.',
			'Breakfast & dinner',
		],
		exclusions: [
			'Personal expense such telephonic calls, camera,Laundry charges, internet, tips, etc. meals which are not mentioned',
			'Anything not mentioned in "Inclusions"',
		],
		hotels: [
			'Port Blair :- Sea Hills Hotels',
			'Port Blair Havelock:- Ocean Pearl Beach Resort ',
			'Neil Island:- Holiday Inn Beach Resort',
		],
	},
	{
		activities: ['water sports', 'camping', 'underwater diving'],
		tags: ['international', 'honeymoon', 'bachelors'],
		slug: 'bangkok-pattaya',
		src: '/destinations/bangkokpattaya.jpg',
		name: 'Bangkok Pattaya',
		duration: '4 nights, 5 days',
		d_days: 5,
		price: 30000,
		available: {
			jan: true,
			feb: true,
			mar: true,
			apr: true,
			may: true,
			jun: true,
			jul: true,
			aug: true,
			sep: true,
			oct: true,
			nov: true,
			dec: true,
		},
		days: [
			{
				day: '1',
				title: 'Pattaya : Arrival and Transfer',
				desc: 'Upon arrival at bangkoks suvarnabhumi international airport, our executive will receive you with a warm welcome. You will be transfer to the hotel in pattaya. Reach in hotel, check into the hotel and have some rest. Later you will be taking to alcazar show to experience the traditional dance show of thailand',
			},
			{
				day: '2',
				title: 'Pattaya : Coral Island Tour',
				desc: 'Have a healthy breakfast at the pattayas hotel. Today you will be taking a day tour to coral island with lunch on speed boat (sic). Visit the coral island to get the thrilling experience in the beautiful beaches. Later you can enjoy a lunch on the speed boat. By evening you will be escort back to hotel and have some rest. Stay overnight at the hotel of pattaya.',
			},
			{
				day: '3',
				title: 'Pattaya : Tour to nongnooch village',
				desc: 'Have a healthy breakfast at the pattayas hotel. Today you will be taking a day tour to nongnooch village have the lunch and show sic where you can get the new experiences in life. By evening you will be escort back to hotel and have some rest. Stay overnight at the hotel of pattaya.',
			},
			{
				day: '4',
				title: 'Pattaya : Explre the city',
				desc: 'Have a healthy breakfast at the pattayas hotel. Today is leisure time you can explore the pattaya city.',
			},
			{
				day: '5',
				title: 'Bangkok : Airport Transfer',
				desc: 'Have a healthy breakfast at the pattayas hotel then check out from the hotel of pattaya. Today you will be transferred bangkoks airport for departure.',
			},
		],
		inclusions: [
			'4 nights accommodation in pattaya.',
			'5 buffet breakfast at hotel (kindly check the timings & venue from the hotel).',
			'Coral island tour (max. 4 hours) by normal boat.',
			'Underwater world tour.',
			'Airport transfers.',
			'All tours & transfers on seat in coach (shared) basis.',
			'All hotel taxes & service charges.',
			'Airport taxes.',
			'GST%.',
		],
		exclusions: [
			'On arrival visa fee of 2000 thai baht (to be paid directly by the guest at thailand airport) or visa fee from india rs. 4,000/- (per person) extra.',
			'Any services not mentioned in the inclusions.',
			'Travel insurance.',
			'Any expenses of personal nature such as- tip to drivers / guides / representative, laundry',
			'Expenses, wines, mineral water, food and drinks not in the regular menus provided by us.',
			'Surcharges (if any).',
			'TCS* 5% will be applicable on the total package cost. -tax collected at source is the tax payable by a seller which he collects from the buyer at the time of sale. *with a view to widen the tax-net, the indian govt. (vide the finance act, 2020) has extended the scope of tax collected at provisioned under section 206(C) of the income-tax act, 1961',
		],
		hotels: null,
	},
	{
		activities: ['boating', 'camping', 'trekking'],
		tags: ['domestic', 'pilgrimage', 'family', 'honeymoon'],
		slug: 'kerala',
		src: '/destinations/kerala.jpg',
		name: 'Kerala',
		duration: '5 nights, 6 days',
		d_days: 6,
		price: 15000,
		available: {
			jan: true,
			feb: true,
			mar: true,
			apr: true,
			may: true,
			jun: true,
			jul: true,
			aug: true,
			sep: true,
			oct: true,
			nov: true,
			dec: true,
		},
		days: [
			{
				day: '1',
				title: 'Kerala : Arrival and Transfer',
				desc: 'Pick up from cochin airport/station and transfers to munnar stay at hotel',
			},
			{
				day: '2',
				title: 'Kerala : Sight-seeing',
				desc: 'Breakfast after breakfast proceed for sightseeing. Mattupetty dam, echo point, kundala dam, Pothamedu view point, blossom park etc are some of the highlights of the sightseeing. Shopping tea museum Stay at munnar',
			},
			{
				day: '3',
				title: 'Kerala : Wildlife encounter',
				desc: 'Check out and drive to thekkady. Thekkady is a world famous wildlife sanctuary and it is also called as periyar. On arrival check in hotel afternoon proceed for a game viewing cruise on the periyar lake. Here you will be able to see a large variety of wildlife, which include elephants, monkeys, deer, wild boar etc evening you can take a elephant ride at periyar wild life and rest of the day is at leisure. Stay at thekkady',
			},
			{
				day: '4',
				title: 'Kerala : Backwaters',
				desc: 'Check out and proceed to alleppey Check in and later proceed to visit alleppey backwaters. Take a cruise Through the rich and splendid backwater. Just relax at the boat. It will be a unique and exclusive experience in your lifetime. Stay at alleppey',
			},
			{
				day: '5',
				title: 'Kerala : Waterfall',
				desc: 'Check out and proceed to visit anthirapally waterfall Stay at cochin',
			},
			{
				day: '6',
				title: 'Kerala : Departure',
				desc: 'Breakfast check out and drive to railway station for departure trips end with wonderful memories of kerala.',
			},
		],
		inclusions: [
			'Pick up & drop from airport/station/bus stand 2 night stay at munnar 1 night stay at thekkady 1 night stay at alleppey',
			'1 night stay at cochin',
			'All transfers & sightseeing',
			'4 breakfast / 4dinner at hotel',
			'1 breakfast, 1 lunch and 1 dinner at houseboat',
			'Toll, parking & state taxes free use of swimming pool ( if its available on chosen property and in operational)',
		],
		exclusions: [
			'5% gst personal expenses any cost arising due to natural calamities like landslides, road blocks etc. To be borne by the client directly on the spot entry tickets of monuments, parks, museums etc anything not mentioned in inclusions',
		],
	},
	{
		activities: ['boating', 'camping', 'trekking'],
		tags: ['domestic', 'family', 'honeymoon'],
		slug: 'meghalaya',
		src: '/destinations/meghalaya.jpg',
		name: 'Meghalaya',
		duration: '7 nights, 8 days',
		d_days: 8,
		price: 22000,
		available: {
			jan: true,
			feb: true,
			mar: true,
			apr: true,
			may: true,
			jun: true,
			jul: true,
			aug: true,
			sep: true,
			oct: true,
			nov: true,
			dec: true,
		},
		days: [
			{
				day: '1',
				title: 'Guwahati : Arrival and Transfer',
				desc: 'Arrive at guwahati airport/railway station. Our representative will be there to greet you and drive you to shillong (from guwahati airport 120kms/4hrs & guwahati railway station 100 kms/3.5 hours). Evening check-in at hotel/resort/guest house for an overnight stay in shillong. Evening free for leisure.',
			},
			{
				day: '2',
				title: 'Shillong : City tour',
				desc: "Shillong the gorgeous city offers amazing tourist spots. The citys own wards lake is popular for short garden walks & boating. Lady hydari park is a japanese style landscaped park endowed with stretches of roses & exquisite flowers. The mini zoo adjacent to the park has several birds & mammals. One of the largest golf courses in asia is an 18 hole golf course is charted amidst a surging valley full of thick pine groves & rhododendron trees. The 'gleneagles of the east' lies in the centre of a plateau surrounded by khasi hills. The state museum & don bosco museum offer insights into the lifestyle and heritage of the people of meghalaya and the northeast of india. Evening free for leisure. Overnight stay at shillong.",
			},
			{
				day: '3',
				title: 'Sohra : Sight-seeing',
				desc: 'After breakfast, relax and drive around sohra and witness its beautiful natural surroundings. Enjoy a pleasant drive to see waterfalls & gorges. Sohra - the wettest place on earth offers roaring waterfalls, limestone caves, living root bridge, galore of water & adventure activities. Witness the gorgeous seven sisters falls & visit the mawsmai cave & thangkharang park. Overnight stay in cherrapunjee.',
			},
			{
				day: '4',
				title: 'Cherrapunjee-Mawlynnong-Shillong',
				desc: 'Post breakfast, start for a tour in and around mawlynnong evening drive to shillong for overnight stay village. Mawlynnong village has earned the distinction of being the cleanest village in asia. It is situated 90 kms. From shillong and besides the picturesque village, offers many interesting sights such as the living root bridge and another strange natural phenomenon of a boulder balancing on another rock. Be two places at once at the international border of india and bangladesh in tamabil and enjoy local boating at the crystal clear water of the umngot river.',
			},
			{
				day: '5',
				title: 'Shillong-Smit-Shillong',
				desc: 'An easy excursion to smit which is the seat of khasi royalty and tradition. Enjoy the serene beauty of the villages and enjoy a picnic lunch at the beautiful surrounding of the laitlum valley. Afternoon return to shillong for local archery. Enroute sweet falls, everliving museum & shillong peak. Overnight at hotel/resort in shillong.',
			},
			{
				day: '6',
				title: 'Shillong-Mawphlang-Mawsynram-Shillong',
				desc: 'After breakfast,startforthe mawphlang sacred forest, a unique wayof preserving nature. This grove has also been named as natures own museum as it has various types of plants, flowering trees, orchids and butterflies. After the sacred grove, we move on to mawsynram to visit the mawjymbuin cave and the mawlongbna village. Evening return to shillong. Overnight at hotel/resort in shillong.',
			},
			{
				day: '7',
				title: 'Shillong-Jaintia hills-Shillong',
				desc: 'After breakfast, drive to the jaintia hills, home of the jaintia tribes of meghalaya. Places of interest thadlaskein lake, tyrshi falls, durga temple, nartiang monolith park and lalong park. Evening return to shillong. Overnight at hotel/resort in shillong.',
			},
			{
				day: '8',
				title: 'Departure',
				desc: 'After breakfast, start on time for guwahati airport (120 km/4 hours drive) for the evening flight.',
			},
		],
		inclusions: [
			'SUV',
			'Fuel',
			'Breakfast & dinner',
			'Pickup and drop from railway station/airport',
			'Tour guide',
			'Hotel stays',
			'Driver',
			'Toll and parking charges',
		],
		exclusions: [
			'Meals which are not mentioned in inclusions. Any personal expenses like laundry, telephone bills, any tips',
			'Any cost arising due to natural calamities like landslides, roadblocks. Etc. (to be borne by the client directly on thespot.)',
			'Tip to driver and tour escort person.',
			'Any other item which is not specified under cost inclusions.',
			'All applicable taxes.',
			'Any entrance fee to the monastery and monuments. Travel insurance.',
		],
		hotels: null,
	},
	{
		activities: ['water sports', 'camping', 'underwater diving'],
		tags: ['international', 'honeymoon', 'bachelors'],
		slug: 'phuket-krabi',
		src: '/destinations/phuketkrabi.jpeg',
		name: 'Phuket Krabi',
		duration: '5 nights, 6 days',
		d_days: 6,
		price: 35000,
		available: {
			jan: true,
			feb: true,
			mar: true,
			apr: true,
			may: true,
			jun: true,
			jul: true,
			aug: true,
			sep: true,
			oct: true,
			nov: true,
			dec: true,
		},
		days: [
			{
				day: '1',
				title: 'Phuket : Arrival and Transfer',
				desc: 'On arrival at phuket airport complete your immigration process and rtpcr test then transfer to hotel. Check in hotel. Evening free at patong beach area. Overnight stay at phuket',
			},
			{
				day: '2',
				title: 'Phi Phi Island Tour',
				desc: 'After morning breakfast at hotel. Proceed for phi phi island tour. Pass through and enjoy the beautiful view of phi phi lay, loh samah bay, and pileh cove & viking cave, ton sai bay or monkey beach. Phi phi islands gives you a wonderful opportunity to take in the majestic sun, go beach hopping or simply enjoy the great outdoors in some of the most beautiful scenery in asia. Surround yourself with white sandy beaches, impressive cliffs, and crystal clear water. Enjoy a delicious lunch at phi phi island. Return back to hotel. Overnight stay at phuket.',
			},
			{
				day: '3',
				title: 'Transfer to Krabi',
				desc: 'After morning breakfast checkout from hotel and transfer to krabi. Pick up from hotel (joint tour with micro bus) including land package rate. Entry fee (ship ticket) including land package rate. Receive krabi ship terminal and transfer to hotel. On arrival check in hotel. Rest of the day at leisure. Overnight stay at krabi',
			},
			{
				day: '4',
				title: 'Krabi : 4 Island Tour',
				desc: 'After morning breakfast at hotel, proceed to full day tour of four island by speed boat. The four islands are koh poda, koh gai (chicken island), koh tub and koh mor. Krabi 4 islands tour is known for its beautiful and scenic islands that are something unique and wonder of nature by all means. Enjoy buffet lunch. Back to hotel. Overnight stay at krabi.',
			},
			{
				day: '5',
				title: 'Krabi : Leisure Day',
				desc: 'Morning breakfast at hotel. Spend your time in leisure or you can explore krabi.',
			},
			{
				day: '6',
				title: 'Departure',
				desc: 'Morning breakfast at hotel.Checkout from hotel.Drop to krabi airport for sweet home.Trip end.',
			},
		],
		inclusions: [
			'2 nights accommodation in phuket.',
			'3 nights accommodation in krabi. ',
			'5 buffet breakfast at hotel (kindly check the timings & venue from the hotel). ',
			'Flight ticket',
			'Airport transfers.',
			'All tours & transfers on seat in coach (shared) basis.',
			'All hotel taxes & service charges',
			'Airport taxes. ',
			'GST%.',
		],
		exclusions: [
			'On arrival visa fee of 2000 thai baht (to be paid directly by the guest at thailand airport) or visa fee from india 4,000INR (per person) extra. ',
			'Any services not mentioned in the inclusions. ',
			'Travel insurance.',
			'Any expenses of personal nature such as : tip to drivers / guides/ representative, laundry expenses, wines, mineral water, food and drinks not in the regular menus provided by us.',
			'Surcharges (if any).',
		],
		hotels: null,
	},
	{
		activities: ['camping', "safari'"],
		tags: ['domestic', 'family'],
		slug: 'rajasthan',
		src: '/destinations/rajasthan.jpg',
		name: 'Rajasthan',
		duration: '8 nights, 9 days',
		d_days: 9,
		price: 25000,
		available: {
			jan: true,
			feb: true,
			mar: true,
			apr: true,
			may: true,
			jun: true,
			jul: true,
			aug: true,
			sep: true,
			oct: true,
			nov: true,
			dec: true,
		},
		days: [
			{
				day: '1',
				title: 'Jaipur: joyous tour begins fun starts from the first day itself',
				desc: 'On arrival in jaipur, you will be received by the agents representative who will help you in getting transferred to your hotel. As you reach the hotel, check in and relax for a while. Later, the first day of your 9-day rajasthan family package you will proceed to birla temple - one of the largest temples in jaipur. After this, you will be taken to nahargarh fort which is known for stunning sunset views of the city. Last but not the least, you visit chokhi dhani, the best luxury resort in jaipur. Enjoy camel ride, authentic rajasthani cuisines and live music performances. As the day ends and night falls, get back to your hotel for a comfortable overnight stay.',
			},
			{
				day: '2',
				title: 'Jaipur: sightseeing tour enjoy the sightseeing tour of the pink city',
				desc: 'Have a scrumptious breakfast at the hotel and then set out for a day tour of forts and monuments in & around jaipur. It starts with an excursion to the historical and expansive amber fort where you can enjoy an elephant ride. Next, you will visit the majestic jaigarh fort that houses the largest cannon on wheels in the world. Be dazed by the astonishing architecture of hawa mahal before shopping at the adjoining jewellery market, johari bazaar. At the end of the second day of this rajasthan tour package, you will be transferred back to your hotel for a comfortable overnight stay. Tip: carry shades or hat to protect yourself from sunlight while touring the city in the daytime',
			},
			{
				day: '3',
				title: 'Bikaner: off to the magical city the third day of your rajasthan holiday itinerary takes you to bikaner',
				desc: 'Wake up to a wholesome breakfast at the hotel and get ready to check out as now you will be transferred to the next destination - bikaner. Enjoy this once-in-a-while road journey from jaipur to bikaner. Upon your arrival at the hotel in bikaner, check in and relax for some time. In the afternoon, the tour itinerary takes you to karni mata temple which is known for thousands of rats in its premise. After the temple tour, return to the hotel for a comfortable overnight stay at the hotel.',
			},
			{
				day: '4',
				title: 'Jaisalmer',
				desc: 'Forts & historical structures have a hearty breakfast at the hotel and then check out as now its time to leave for the next destination - the city of jaisalmer. As you reach your hotel in jaisalmer, check in and relax. Later in the day, visit the famous jaisalmer fort built by the founder of the jaisalmer city, rao jaisal. As the tour continues, also visit famous havelis like patwon ki haveli, salim singh haveli & more. Before the evening begins to set in, enjoy spending some time at the gadisar lake in the evening. As the dusk falls, get back to the hotel for overnight stay.',
			},
			{
				day: '5',
				title: 'Jaisalmer: explore the thar desert',
				desc: 'Post breakfast get ready to visit bada bagh which is an expansive garden complex and is a true delight for history lovers. In the evening, proceed to sam sand dunes and enjoy the exciting experience of camel safari. Relish the picture-perfect sunset views and enjoy the folk music. As the day ends, enjoy a sumptuous dinner and a relaxing overnight stay in the swiss tents.',
			},
			{
				day: '6',
				title: 'Jodhpur: ancient forts, palaces, and much more',
				desc: "Have a delectable breakfast at the hotel and then check out as now you will be heading to jodhpur. Later on, head to the gigantic mehrangarh fort from where you can enjoy the top-view of the sun city'. Mehrangarh fort is one of the biggest fort of india depicting the bravery, culture and rich history of jodhpur. Also, visit jaswant thada which was built by king sardar singh in the memory of late king jaswant singh. Later, you will visit umaid bhawan palace museum which is a part of the luxurious hotel umaid bhawan palace. Shop around the local market in jodhpur before you are transferred to your hotel for a cozy overnight stay",
			},
			{
				day: '7',
				title: 'Udaipur: welcome to the city of lakes',
				desc: 'Have filling breakfast and get ready to check out as its time to get moving to one of the loveliest cities in rajasthan- udaipur. Known for its lakes and rich history, udaipur has many telling tales of the rajput era. On reaching udaipur, check into the hotel and relax for a while. As the day progresses you will be taken for an excursion to eklingji & nagda temples. As the day ends, return to the hotel for an overnight stay.',
			},
			{
				day: '8',
				title: 'Udaipur: day for sightseeing',
				desc: 'After breakfast leave for a sightseeing tour around udaipur. You can begin with a visit to saheliyon-ki-bari. As the tour continues, you will visit attractions like museum of folk art which is famous for its wide collection of puppets, folk dresses, dolls, ornaments, paintings and folk musical instruments. Later, you can visit the city palace which is known to be the biggest palace complex in india. In the evening, you will get to enjoy a fun-filled boat ride at pichola lake which is the star attraction of udaipur. Return to hotel for comfortable overnight stay.',
			},
			{
				day: '9',
				title: 'Udaipur: good bye, rajasthan!',
				desc: 'After a hearty breakfast at the hotel, check out from the hotel and get transferred to the airport / railway station for your journey back home.',
			},
		],
		inclusions: [
			'Airport/railway station transfers',
			'Breakfast & dinner',
			'Sightseeing guide',
			'English speaking driver trip supplements',
			'Cultural program',
			'Camel safari',
			'Jaipur : pearl palace heritage/similar',
			'Bikaner : hotel continental blue/similar',
			'Jaisalmer : maharaja desert camp/similar',
			'Jodhpur : the prem beacon/similar',
			'Udaipur : hotel royal palm/similar',
		],
		exclusions: [
			'Personal expense such telephonic calls, camera,Laundry charges, internet, tips, etc. meals which are not mentioned',
			'Anything not mentioned in "Inclusions"',
		],
		hotels: null,
	},
	{
		activities: ['camping', "safari'"],
		tags: ['international', 'family'],
		slug: 'dubai-abudhabi',
		src: '/destinations/dubai.jpg',
		name: 'Dubai and Abu Dhabi',
		duration: '4 nights, 5 days',
		d_days: 5,
		price: 40000,
		available: {
			jan: true,
			feb: true,
			mar: true,
			apr: true,
			may: true,
			jun: true,
			jul: true,
			aug: true,
			sep: true,
			oct: true,
			nov: true,
			dec: true,
		},
		days: [
			{
				day: '1',
				title: 'Dubai : Arrival',
				desc: 'meet & greet at the airport transfer to your hotel overnight leisure in dubai',
			},
			{
				day: '2',
				title: 'Dubai : Modern Dubai and Burj Khalifa',
				desc: 'Burj Khalifa (124th floor) Burjal Arab (photo stop) thepalm jumeirah theatlantis hotel (photo stop) dhow cruise in dubai marina dubaimalland fountainshow overnight in dubai. Discover the bustling metropolis of dubai with its dazzling skyline and amazing architecture. Visit the worlds tallest building, the burjkhalifa; spot the largest aquarium in the world and get fascinated by the most expensive hotel in dubai, burjal arab (photo stop only).',
			},
			{
				day: '3',
				title: 'Dubai : Desert Safari',
				desc: 'Desert safari by 4x4 sunset in the desert camel ride belly dance and tanoura dance bbqdinner in a beduine camp. The desert safari is a classic, must-do arabia experience. Thrilling dune drive, magic show with belly dancing and delicious bbq dinner buffet in a bedouin camp. Unforgettable!',
			},
			{
				day: '4',
				title: 'Abu Dhabi : City Tour',
				desc: 'Discoverabu dhabi, the capital of the united arab emirates and witness the perfect combination of the ancient past with the modern present. Admireworlds 8th largest mosqueand its amazingchandelier withswarovskicrystals. Visitmarina circuit and takea photo of theformula1 track.',
			},
			{
				day: '5',
				title: 'Departure',
				desc: 'Breakfast and transfer to the airport',
			},
		],
		inclusions: [
			'4 overnights in your booked hotel category (4 or 5 hotel) ',
			'meal plan as per itinerary : b = breakfast (4x), d = dinner (1x) ',
			'transfer from/to dubai airport ',
			'modern dubai city tour withburj khalifa ticket (124th floor) ',
			'cruise in the dubai marina with soft drinks (30 minutes) ',
			'desert safari with bbq dinner and soft drinks ',
			'modern abu dhabi city tour ',
			'tea time in the emirates palace hotel (coffee or tea and a piece of cake) ',
			"soft drinks in viceroy hotel terrace (views on F1 track) '",
			'english/german speaking licensed guide (other languages upon request)',
		],
		exclusions: [
			'Personal expense such telephonic calls, camera,Laundry charges, internet, tips, etc. meals which are not mentioned',
			'Anything not mentioned in "Inclusions"',
		],
		hotels: null,
	},
	{
		activities: ['trekking'],
		tags: ['domestic', 'family', 'pilgrimage'],
		slug: 'kedarnath-from-delhi',
		src: '/destinations/kedarnath1.jpeg',
		name: 'Kedarnath Yatra from Delhi',
		duration: '5 nights, 6 days',
		d_days: 6,
		price: 12000,
		available: {
			jan: false,
			feb: false,
			mar: false,
			apr: true,
			may: true,
			jun: true,
			jul: true,
			aug: true,
			sep: true,
			oct: true,
			nov: false,
			dec: false,
		},
		days: [
			{
				day: '1',
				title: 'Delhi-Rishikesh (245km ~5hours)',
				desc: 'Today start your journey to rishikesh from delhi. In the evening attend the ganga aarti at har-ki-pauri. And hotel dinner and overnight stay at hotel.',
			},
			{
				day: '2',
				title: 'Rishikesh-Guptkashi (180km ~7hours)',
				desc: 'Start drive from rishikesh to guptkashi. On arrival check-in at hotel for overnight stay. The evening is free to visit the vishwanath temple.',
			},
			{
				day: '3',
				title: 'Guptkash-Gaurikund (30km ~2hours)',
				desc: 'Start the drive at 0530 hrs sharp to gaurikund. Sonprayag is the closest stop before gaurikund at distance of 06 kms. Private vehicles are allowed only till sonprayag. Hire the local vehicle from sonprayag to gaurikund. Upon arrival start the trek on the zigzag and well laid trail to kedarnath or there are other options of pony or doli available on rent. On arrival check-in at hotel, freshen up and visit kedarnath ji. Pay homage to divine statue of nandi bull, located at the temple entrance gate. Attend the evening arti and offer your prayers to lord shiva. You can also visit adi shankaracharya samadhi, the grave of adi guru shankaracharya, located at the premises of kedarnath temple which is also one of the most popular spot at kedarnath. After offering prayers get back to hotel for an overnight stay.',
			},
			{
				day: '4',
				title: 'Kedarnath-Guptkash (50km ~6hours)',
				desc: 'In the morning participate the arti at and abhishek at kedarnath temple & take blessing from kedarnath ji. Latter after breakfast trek down to same way where you come from. On arrival gaurikund drive to guptkashi and check into a hotel followed by dinner & overnight stay.',
			},
			{
				day: '5',
				title: 'Guptkash-Rishikesh (200km ~8hours)',
				desc: 'After having breakfast drive towards rishikesh, an overnight stay.',
			},
			{
				day: '6',
				title: 'Rishikesh-Delhi (240km ~10hours)',
				desc: 'After having breakfast drive towards delhi via rishikesh, haridwar.',
			},
		],
		inclusions: [
			'Accommodation in above mention hotels.',
			'Meals: breakfast & dinner',
			'Transportation services by (innova/indigo/swift dzire/etios/tempo traveler).',
			'All toll, tax, parking and driver allowances are included.',
		],
		exclusions: [
			'Govt. Service tax, (g.S.T)',
			'Any international or domestic air or rail tickets.',
			'Extra meals/drinks not mentioned.',
			'Any expenses of laundry, porter, pony / palaki, tips, camera fee, ropeway charges, entrance charges.',
			'Any travel, medical health insurance or any other expenses incurred due to bad weather, road closure, landslides, etc.',
			'Anything not specified in cost included.',
		],
		hotels: [
			'Rishikesh (2N)- Hotel chandra palace / similar',
			'Guptkashi (2N)- Hotel green valley / similar',
			'Kedarnath (1N)-bikaner house / similar',
		],
	},
	{
		activities: ['trekking'],
		tags: ['domestic', 'family', 'pilgrimage'],
		slug: 'kedarnath-from-haridwar',
		src: '/destinations/kedarnath2.jpg',
		name: 'Kedarnath Yatra from Haridwar',
		duration: '3 nights, 4 days',
		d_days: 4,
		price: 10000,
		available: {
			jan: false,
			feb: false,
			mar: false,
			apr: true,
			may: true,
			jun: true,
			jul: true,
			aug: true,
			sep: true,
			oct: true,
			nov: false,
			dec: false,
		},
		days: [
			{
				day: '1',
				title: 'Haridwar-Guptkashi (205km ~8hours)',
				desc: 'Today start your journey to Guptkashi from Haridwar and overnight stay at in hotel.',
			},
			{
				day: '2',
				title: 'Guptkashi-Gaurikund (30km ~2hours)',
				desc: 'Start the drive at 0530 hrs sharp to Gaurikund. Son prayag is the closest stop before Gaurikund at distance of 06Kms. Private Vehicles are allowed only till Sonprayag. Hire the local vehicle from Sonprayag to Gaurikund. Upon arrival start the trek on the zigzag and well laid trail to Kedarnath or there are other options of pony or Doli available on rent. On arrival check-in at hotel, freshen up and visit Kedarnath Ji. Pay homage to divine statue of Nandi bull, located at the temple entrance gate. Attend the evening Arti and offer your prayers to Lord Shiva. You can also visit Adi Shankaracharya Samadhi, the grave of Adi Guru Shankaracharya, located at the premises of Kedarnath temple which is also one of the most popular spot at Kedarnath. After offering prayers get back to hotel for an overnight stay.',
			},
			{
				day: '3',
				title: 'Kedarnath-Guptkashi (50km ~6hours)',
				desc: 'In the morning participate the arti at and abhishek at Kedarnath temple & take blessing from Kedarnath ji. Latter after breakfast trek down to same way where you come from. On arrival Gaurikund Drive to Guptkashi and check into a hotel followed by dinner & overnight stay.',
			},
			{
				day: '4',
				title: 'Guptkashi-Haridwar (200km ~5hours)',
				desc: 'In the morning participate the arti at and abhishek at kedarnath temple & take blessing from kedarnath ji. Latter after breakfast trek down to same way where you come from. On arrival gaurikund drive to guptkashi and check into a hotel followed by dinner & overnight stay.',
			},
		],
		inclusions: [
			'Accommodation in above mention hotels.',
			'Meals: breakfast & dinner',
			'Transportation services by (innova/indigo/swift dzire/etios/tempo traveler).',
			'All toll, tax, parking and driver allowances are included.',
		],
		exclusions: [
			'Govt. Service tax, (g.S.T)',
			'Any international or domestic air or rail tickets.',
			'Extra meals/drinks not mentioned.',
			'Any expenses of laundry, porter, pony / palaki, tips, camera fee, ropeway charges, entrance charges.',
			'Any travel, medical health insurance or any other expenses incurred due to bad weather, road closure, landslides, etc.',
			'Anything not specified in cost included.',
		],
		hotels: [
			'Guptkashi (2N)- Hotel green valley / similar',
			'Kedarnath (1N)-bikaner house / similar',
		],
	},
	{
		activities: ['trekking', 'adventure sports'],
		tags: ['domestic', 'family', 'honeymoon'],
		slug: "shimla-manali'",
		src: '/destinations/shimlamanali.jpeg',
		name: 'Shimla and Manali',
		duration: '5 nights, 6 days',
		d_days: 6,
		price: 12000,
		available: {
			jan: true,
			feb: true,
			mar: true,
			apr: true,
			may: true,
			jun: true,
			jul: true,
			aug: true,
			sep: true,
			oct: true,
			nov: true,
			dec: true,
		},
		days: [
			{
				day: '1',
				title: 'Shimla',
				desc: 'After pick-up from chandigarh railway station, your journey starts towards shimla,after reaching check-in to the hotel and freshen up for the local sightseeing of shimla and explore the mountains.',
			},
			{
				day: '2',
				title: 'Sightseeing in shimla & Kufri',
				desc: 'Freshen up before going on a sightseeing tour in and around the town. This day after fresh n up proceed for in and around sightseeing of shimla, visit Kufri, indias one of the best holiday paradise kufri in shimla is beautifully tucked on an altitude of 2622 meter. The place is a tourist hotspot for its awesome scenic and sports activities. Evening free to stroll in the famous shopping place of Shimla town - "The mall & the ridge" this large open space in the heart of town presents excellent views of the mountain ranges. Shimlas landmarks - the neo- gothic structure of christ church and the neo - tudor library building- are worth seeing. Overnight stay at the hotel in shimla. Sightseeing for the day: mall road => ridge => christ church => gaiety theatre => scandal point => kali bari temple => wood market => jansi park sightseeing for the day: => kufri => green valley => chini bungalow => mini zoo => fun word',
			},
			{
				day: '3',
				title: 'Shimla to Manali',
				desc: 'Today after breakfast proceed to shimla to manali after breakfast leave for manali, on the way sight-seeing like (sundernagar lake, pandoh dam, vaishno devi temple) and overnight stay in manali. Sightseeing for the day:- Sundernagar lake => pandoh dam => vaishno devi temple => kullu valley',
			},
			{
				day: '4',
				title: 'Sissu valleys charms solang valley - Sissu valleys charms - Solang valley',
				desc: "Today after breakfast proceed to sissu through atal tunnel. Sissu (also known as khwaling) is a small town in the lahaul valley and also the other part of rohtang pass. It is around 40 km from manali and is located on the right bank of the chandra river. In sissu excursion we will visit sissu lake, sissu waterfall across the chandra river and opposite the town, locally known as 'palden lhamo dhar'. While coming back to manali you will visit solang valley that is famous for its picturesque location and adventurous activities. You can enjoy lots of activities like river crossing, rock climbing, rappelling, paragliding, mountain bike, zorbing, hot air ballooning, pony riding, and cable car (at your own cost). Once you come back, enjoy the daily rooftop party at hotel, have dinner and relax overnight in the hotel.",
			},
			{
				day: '5',
				title: 'Manali Local & Rohtang',
				desc: 'Freshen up before going on a sightseeing tour in and around the town. The dexcursion includes a visit to mall road, the himalayan nyingamapa gompa (tibetian monestry), it was constructed in the year 1969. The architecture of the monastery represents the tibetan style of architecture designed with hued frescoes. The club house, is an amusement and adventure retreat set up on the banks of the manalsu nala, a branch of the breathtakingbeas river. Hadimba devi temple was built in 1553 ce by maharaja bahadur singh. It is built around a cave where devi hidimba performed meditation. Hidimba was married to bhima and gave birth to their son ghatotkach. Vashisht temple, the village of vashisht was named after rishi vashisht one of the seven sages of hindu.',
			},
			{
				day: '6',
				title: 'Drop back to chandigarh railway station/airport',
				desc: 'After breakfast checkout from the hotel and leave for your hometown with sweet memories.',
			},
		],
		inclusions: [
			'Pick up from shimla toy train station and private cab for sightseeing in shimal and manali, shimla to manali transfer.',
			'Accommodation in hotel as per the variant selected 01 nights accommodation in shimla and 02 nights accomodation in manali on double share( for couple) and triple/quad share for others basis. Buffet breakfast and dinner on all days as per the itinerary',
			'Daily rooftop music night at manali. (depends on weather) highly-experienced driver cum guide dall sightseeing & transfers (as per itinerary) arrival/ departure assistance. 3 breakfast & 3 dinner.',
			'All toll tax, parking, fuel and driver allowances',
		],
		exclusions: [
			'Personal expenses such as minibar, mineral water, drinks, laundry, phone call, camera fees, or any other item all such expenses will have to be paid directly.',
			'All entry tickets for stupas, monasteries, sightseeing entry fee, activities!',
			'Lunch throughout the tour.',
			'Meals that are not mentioned in the inclusions & tips. International / domestic airfare, visa fees, airport tax, or any kind of insurance cover',
			'Liability for change in itinerary due to reasons beyond our control like change in flight & train schedule, cancellation of flights/trains; political disturbances; natural phenomena, etc',
		],
		hotels: null,
	},
];

export const notes = [
	'Rates not valid for peak festive season I.E. New year, diwali, pushkar fair etc',
	'Rates are based on hotels subject to availability at the time of making reservation. In case of unavailability in mentioned hotels, alternate accommodation will be arranged in a similar category hotel rates are subject to change if there is any fair & festival, major conference, events in the travel destination ',
	'Early check-in / late checks out is subject to availability of rooms',
	'Cancellation charges would be as per the company policy.',
	'Vehicle confirmed will be as per itinerary and not at disposal.',
	'All sightseeing mentioned are subject to weather conditions, political conditions & traffic conditions in the destination. ',
	'Any sightseeing missed due to natural calamities/weather conditions is non-refundable. ',
	'All entrances fees will be on direct payment basis as per itinerary',
];

export const cancellation = [
	'Cancellation prior to departure/check-in date booking amount not refundable.',
	'If cancellations are made 30 days before the start date of the trip, 40% of total tour cost will be charged as cancellation fees.',
	'If cancellations are made 15-30 days before the start date of the trip, 80% of total tour cost will be charged as cancellation fees.',
	'If cancellations are made within 0-15 days before the start of the trip, 100% of total tour cost will be charged as cancellation fees.',
];
